name: Decode gradle-wrapper.jar

on:
  workflow_dispatch:

jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Decode gradle-wrapper.jar.b64
        run: |
          mkdir -p gradle/wrapper
          base64 -d gradle-wrapper.jar.b64 > gradle/wrapper/gradle-wrapper.jar

      - name: Show JAR info
        run: file gradle/wrapper/gradle-wrapper.jar
