name: Init Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  setup-gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Gradle CLI
        uses: gradle/gradle-build-action@v2

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.2.1

      - name: Commit Gradle Wrapper
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add gradle/wrapper/ gradlew gradlew.bat
          git commit -m "Add Gradle wrapper files"
          git push
